config:
  libraries:
    params:
      config_context_prefix:
      - .toolbox
    cicd:
      params:
        config_context_prefix:
        - cicd
        - .toolbox.cicd
        env:
          VARIANT_CONFIG_DIR: .

      build:
        params:
          config_context_prefix:
          - .toolbox.cicd.build
        deliverables:
          params:
            cmd: build/deliverables
        direct:
          params:
            cmd: build/direct
      deploy:
        params:
          config_context_prefix:
          - .toolbox.cicd.deploy
          cmd: deploy

      component:
        params:
          source: github.com/aroq/toolbox-cicd-build
          image: aroq/toolbox-cicd-build
          tool_dirs:
          - toolbox/.toolbox/deps/toolbox-cicd-build
        commands:
          build:
            params:
              cmd: cicd/component/build
              config_context_prefix:
              - component
              - build

tools:
  cicd/component/build:
    from:
    - config.libraries.cicd.component.commands.build


